### PR TITLE
Add the ability to pass in role_arn and external_id as environment variables

### PR DESCRIPTION
**Pull request by therealnb**
This is a fix for issue #26.

### CODE REVIEW

**Comment by therealnb** [comment]
I don't think these failures are caused by my change - does it normally run without fail?

**Comment by therealnb** [comment]
Is there anyone currently watching this code?
I'm just wondering because I need to know the next steps to get this merged or I need to work on another approach with the existing code.

**Comment by therealnb** [comment]
Is this project still alive?
If I want to make these changes, do I have to make my own fork?
If nobody is managing this project is there a way I can become a submitter?

**Comment by therealnb** [comment]
@brunns is this the live branch, or the one from @l01cd3v [https://github.com/l01cd3v/opinel](https://github.com/l01cd3v/opinel)

**Comment by brunns** [comment]
@therealnb Sorry, I'm not a maintainer here.

**Comment by l01cd3v** [comment]
@therealnb , I no longer work with NCC Group and have been busy with other projects, hence to lack of activity on this project. I was told that NCC Group is looking for a new maintainer, though last time I checked there didn't seem to be anyone who picked up this task yet. I may still contribute to this project though cannot tell how much time I will have to put in this project.

This PR seems pretty straight forward so I'll try to trigger a testrun sometime this week and will merge it if everything passes.

**Pull request merged**
